### ISSUE TITLE
Planetracking code showing error on AR Sparks

### ISSUE THREAD

**Issue by ma0-det0** [jordyhenry/PlaneTracker.trackingMode#1]
<img width="1280" alt="Screenshot 2021-01-14 at 18 54 55" src="https://user-images.githubusercontent.com/77460290/104636204-e8770a80-569a-11eb-8fec-3bcdbb59703a.png">
Hi,

I am having issue with the code..It says :
Error:undefined is not a function
   {
     "line": 6,
     "column": 37,
     "sourceURL": "script.js"
   }

As I have not coding knowledge at all I downloaded form here..attached screenshot of the code line downladed and the AR Sparks error.

it will be great if you can help me with that.

Thanks for your attention

**Comment by jordyhenry** [comment]
I've just deployed two new branches to solve these issues, 

['v104.1'](https://github.com/jordyhenry/PlaneTracker.trackingMode/tree/v104.1) where I've updated the script accordingly to the new API requirements, 
and ['v104-with-patches'](https://github.com/jordyhenry/PlaneTracker.trackingMode/tree/v104-with-patches) where I use the patches for native UI and click to track features, and only use script to set the new tracking mode, which is not possible by patches so far.

Is good to mention that new versions of spark only allow HORIZONTAL PLANES and MOVING OBJECTS tracking, so you may lose VERTICAL PLANES, which is a shame for spark.

Anyway, I hope it helps you or anyone else with the same problem =)
